name = "champ-pm"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "champ-pm"
database_id = "c5073fbd-b4a6-42c3-95de-e3f59b517e5f"

[vars]
CLERK_PUBLISHABLE_KEY = "pk_test_Zml0dGluZy1iYWRnZXItNC5jbGVyay5hY2NvdW50cy5kZXYk"
VITE_CLERK_PUBLISHABLE_KEY = "pk_test_Zml0dGluZy1iYWRnZXItNC5jbGVyay5hY2NvdW50cy5kZXYk"

# Secrets — set via: wrangler pages secret put <NAME>
# CLERK_SECRET_KEY
