-- FY21 FEMA Projects & Tasks (Grant ID 14)
-- Generated 2026-03-07

-- Fix existing Rock Island project (id=1): update budget + add missing tasks
UPDATE projects SET budget=770000.00 WHERE id=1;
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Project Outreach and Communication Plan', 'Rock Island stakeholder engagement', '2025-09-15', NULL, 10000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Event Data Capture (non-CCO / Open House)', 'Rock Island PICC meeting', '2022-12-15', NULL, 10000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Event Data Capture (non-CCO / Open House)', 'Rock Island FRR meeting', '2024-09-15', NULL, 20000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Survey Data Capture', 'Rock Island Survey', '2023-09-15', NULL, 81250.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Independent QA/QC: Survey Data', 'Rock Island Survey QA/QC', '2023-09-15', NULL, 20312.50, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Terrain Data Capture', 'Rock Island Terrain', '2022-12-15', NULL, 12500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Base Map Data Capture', 'Rock Island Aerial photo', '2022-12-15', NULL, 2500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Hydrology Data Capture', 'Rock Island Hydro', '2025-03-15', NULL, 93149.46, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Independent QA/QC: Hydrology Data', 'Rock Island Hydro QA/QC', '2025-03-15', NULL, 9314.95, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Hydraulics Data Capture', 'Rock Island Hydra', '2025-03-15', NULL, 300641.50, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Independent QA/QC: Hydraulics Data', 'Rock Island Hydra QA/QC', '2025-03-15', NULL, 45331.59, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Floodplain Mapping: Redelineation Data Capture - Riverine', 'Rock Island Miss. River Redelineation', '2023-03-15', NULL, 20000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Floodplain Mapping: Redelineation Data Capture - Levee Areas', 'Rock Island Levee Areas Redelineation', '2023-12-15', NULL, 30000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (1, 'Rock Island County, IL', 'Rock Island QR1 Db', '2025-09-15', NULL, 75000.00, 0, 'active');

-- Project: ISWS 21-01
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-01', 'PM SOW 21-01', '2021-12-15', '2023-09-15', 80000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-01' ORDER BY id DESC LIMIT 1), 'State and Local Business Plans and/or updates (required)', 'Business Plan (required)', '2021-12-15', NULL, 25000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-01' ORDER BY id DESC LIMIT 1), 'Global Program Management (required)', 'Program Management Plan (Prof Dev & Conferences IAFSM, ASFPM, ILGISA, Esri, APA, IEMA)', '2023-09-15', NULL, 25000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-01' ORDER BY id DESC LIMIT 1), 'Global Outreach for Mapping', 'Outreach Plan; Report of outreach activities (website overhead, flood alliance support)', '2023-09-15', NULL, 5000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-01' ORDER BY id DESC LIMIT 1), 'Coordinated Needs Management Strategy (CNMS)', 'IL CNMS Updates', '2023-09-15', NULL, 20000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-01' ORDER BY id DESC LIMIT 1), 'Programmatic QA/QC Plans', 'ISWS QA/QC Plans & Checklists', '2022-02-15', NULL, 5000.00, 0, 'active');

-- Project: ISWS 21-03
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-03', '21-03 Whiteside Data Dev-QR1', '2022-12-15', '2025-09-15', 150000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-03' ORDER BY id DESC LIMIT 1), 'Project Management and Earned Value Data Entry', 'Whiteside PM', '2025-09-15', NULL, 25000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-03' ORDER BY id DESC LIMIT 1), 'Project Risk ID & Mitigation', 'Whiteside Prj risk control', '2025-09-15', NULL, 5000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-03' ORDER BY id DESC LIMIT 1), 'Project Outreach and Communication Plan', 'Whiteside Stakeholder engagement', '2025-09-15', NULL, 5000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-03' ORDER BY id DESC LIMIT 1), 'Terrain Data Capture', 'Whiteside Terrain', '2022-12-15', NULL, 7500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-03' ORDER BY id DESC LIMIT 1), 'Base Map Data Capture', 'Whiteside Aerial photo', '2022-12-15', NULL, 2500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-03' ORDER BY id DESC LIMIT 1), 'Floodplain Mapping: Redelineation Data Capture - Riverine', 'Whiteside Miss. River Redelineation', '2023-03-15', NULL, 20000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-03' ORDER BY id DESC LIMIT 1), 'Floodplain Mapping: Redelineation Data Capture - Levee Areas', 'Whiteside Levee Areas Redelineation', '2023-03-15', NULL, 25000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-03' ORDER BY id DESC LIMIT 1), 'Whiteside County, IL', 'Whiteside QR1 Db', '2023-12-15', NULL, 60000.00, 0, 'active');

-- Project: ISWS 21-04
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-04', '21-04 Henry Data Dev-QR1', '2022-12-15', '2025-09-15', 125000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-04' ORDER BY id DESC LIMIT 1), 'Project Management and Earned Value Data Entry', 'Henry PM', '2025-09-15', NULL, 25000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-04' ORDER BY id DESC LIMIT 1), 'Project Risk ID & Mitigation', 'Henry Prj risk control', '2025-09-15', NULL, 5000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-04' ORDER BY id DESC LIMIT 1), 'Project Outreach and Communication Plan', 'Henry Stakeholder engagement', '2025-09-15', NULL, 5000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-04' ORDER BY id DESC LIMIT 1), 'Terrain Data Capture', 'Henry Terrain', '2022-12-15', NULL, 7500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-04' ORDER BY id DESC LIMIT 1), 'Base Map Data Capture', 'Henry Aerial photo', '2022-12-15', NULL, 2500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-04' ORDER BY id DESC LIMIT 1), 'Floodplain Mapping: Redelineation Data Capture - Riverine', 'Henry Green River Redelineation', '2023-03-15', NULL, 20000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-04' ORDER BY id DESC LIMIT 1), 'Henry County, IL', 'Henry QR1 Db', '2023-12-15', NULL, 60000.00, 0, 'active');

-- Project: ISWS 21-05
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-05', '21-05 Stark QR2-Eff', '2022-03-15', '2025-09-15', 175000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Project Management and Earned Value Data Entry', 'Stark PM QR2-Eff', '2025-09-15', NULL, 18000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Project Risk ID & Mitigation', 'Stark Prj risk control QR2-Eff', '2025-09-15', NULL, 5000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Project Outreach and Communication Plan', 'Stark Outreach - Non PPP', '2025-09-15', NULL, 5000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Flood Risk Database', 'Stark FR Db', '2025-03-15', NULL, 3500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'CSLF', 'Stark Comparison map', '2025-03-15', NULL, 1500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Water Surface Elevation Grids', 'Stark WSE Grids', '2025-03-15', NULL, 6000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Flood Depth Grids', 'Stark Depth Grids', '2025-03-15', NULL, 3500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Percent Annual Chance & Percent 30-Year Chance Grids', 'Stark % Grids', '2025-03-15', NULL, 1500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Flood Risk Assessment', 'Stark HAZUS', '2025-03-15', NULL, 3500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'AOMI', 'Stark AOMI', '2025-03-15', NULL, 2500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Floodplain Mapping: Redelineation Data Capture', 'Spoon River Redelineation', '2022-03-15', NULL, 2000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Produce, QR3 and Distribute Prelim Products: Stark County, IL', 'Stark Prelim & Release', '2023-09-15', NULL, 60000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Due Process', 'Stark Due Process', '2024-09-15', NULL, 24000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'CCO Meeting Data Capture', 'Stark CCO & Prep', '2024-03-15', NULL, 7500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Open House', 'Stark Open House & Prep', '2024-03-15', NULL, 7500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-05' ORDER BY id DESC LIMIT 1), 'Final Map Production and Distribution', 'Stark Final & Reval', '2025-09-15', NULL, 24000.00, 0, 'active');

-- Project: ISWS 21-06
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-06', '21-06 Montgomery Data Dev-KDP2', '2023-01-15', '2025-09-15', 400000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Project Management and Earned Value Data Entry', 'Montgomery PM', '2025-09-15', NULL, 23034.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Project Risk ID & Mitigation', 'Montgomery Prj risk control', '2025-09-15', NULL, 3500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Project Outreach and Communication Plan', 'Montgomery Stakeholder engagement', '2025-09-15', NULL, 28500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Event Data Capture (non-CCO / Open House)', 'Montgomery PICC Meeting', '2023-01-15', NULL, 8500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Event Data Capture (non-CCO / Open House)', 'Montgomery FRR Meeting', '2024-03-15', NULL, 20000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Terrain Data Capture', 'Prj Area Terrain', '2023-02-15', NULL, 6000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Base Map Data Capture', 'Montgomery Aerial photo', '2023-02-15', NULL, 1581.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Hydrology Data Capture', 'Montgomery Hydro', '2025-06-15', NULL, 117795.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Independent QA/QC: Hydrology Data', 'Montgomery Hydro QA/QC', '2025-06-15', NULL, 11779.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Hydraulics Data Capture', 'Montgomery Hydra', '2025-06-15', NULL, 163010.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-06' ORDER BY id DESC LIMIT 1), 'Independent QA/QC: Hydraulics Data', 'Montgomery Hydra QA/QC', '2025-06-15', NULL, 16301.00, 0, 'active');

-- Project: ISWS 21-07
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-07', '21-07 Hamilton Data Dev-KDP2', '2023-01-15', '2025-09-15', 400000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Project Management and Earned Value Data Entry', 'Hamilton PM', '2025-09-15', NULL, 27257.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Project Risk ID & Mitigation', 'Hamilton Prj risk control', '2025-09-15', NULL, 7500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Project Outreach and Communication Plan', 'Hamilton Stakeholder engagement', '2025-09-15', NULL, 28500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Event Data Capture (non-CCO / Open House)', 'Hamilton PICC & FRR Meetings', '2023-01-15', NULL, 8500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Event Data Capture (non-CCO / Open House)', 'Hamilton PICC & FRR Meetings', '2024-03-15', NULL, 20000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Terrain Data Capture', 'Prj Area Terrain', '2023-06-15', NULL, 12500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Base Map Data Capture', 'Hamilton Aerial photo', '2023-06-15', NULL, 2500.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Hydrology Data Capture', 'Hamilton Hydro', '2025-06-15', NULL, 26580.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Independent QA/QC: Hydrology Data', 'Hamilton Hydro QA/QC', '2025-06-15', NULL, 2658.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Hydraulics Data Capture', 'Hamilton Hydra', '2025-06-15', NULL, 240005.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-07' ORDER BY id DESC LIMIT 1), 'Independent QA/QC: Hydraulics Data', 'Hamilton Hydra QA/QC', '2025-06-15', NULL, 24000.00, 0, 'active');

-- Project: ISWS 21-08
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-08', '21-08 MidLowWabash DD & Engage', '2024-09-15', '2024-09-15', 150000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-08' ORDER BY id DESC LIMIT 1), 'Project Management and Earned Value Data Entry', 'MidLowWabash Cont. PM', '2024-09-15', NULL, 25000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-08' ORDER BY id DESC LIMIT 1), 'Project Risk ID & Mitigation', 'MidLowWabash Cont. levee status involvement (IL & IN)', '2024-09-15', NULL, 10000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-08' ORDER BY id DESC LIMIT 1), 'Project Outreach and Communication Plan', 'MidLowWabash Cont. stakeholder engagement (IL & IN)', '2024-09-15', NULL, 5000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-08' ORDER BY id DESC LIMIT 1), 'Hydraulics Data Capture', 'MidLowWabash Cont. Hydra & workmaps (IL & IN)', '2024-09-15', NULL, 100000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-08' ORDER BY id DESC LIMIT 1), 'Independent QA/QC: Hydraulics Data', 'MidLowWabash Cont. Hydra QA/QC (IL & IN)', '2024-09-15', NULL, 10000.00, 0, 'active');

-- Project: ISWS 21-09
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-09', '21-09 Peoria Cont. Engagement', '2022-09-15', '2025-09-15', 75000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-09' ORDER BY id DESC LIMIT 1), 'Project Management and Earned Value Data Entry', 'Peoria Cont. PM', '2025-09-15', NULL, 20000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-09' ORDER BY id DESC LIMIT 1), 'Project Risk ID & Mitigation', 'Peoria Cont. levee status involvement', '2025-09-15', NULL, 25000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-09' ORDER BY id DESC LIMIT 1), 'Project Outreach and Communication Plan', 'Peoria Cont. stakeholder engagement', '2025-09-15', NULL, 25000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-09' ORDER BY id DESC LIMIT 1), 'Floodplain Mapping: Redelineation Data Capture', 'Spoon River Redelineation', '2022-09-15', NULL, 5000.00, 0, 'active');

-- Project: ISWS 21-10
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-10', '21-10 Bond Cont. DD&Engagement', '2022-08-15', '2024-09-15', 50000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-10' ORDER BY id DESC LIMIT 1), 'Project Management and Earned Value Data Entry', 'Bond Cont. PM', '2024-09-15', NULL, 2000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-10' ORDER BY id DESC LIMIT 1), 'Project Risk ID & Mitigation', 'Bond Cont. levee status involvement - Keyesport', '2024-09-15', NULL, 2000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-10' ORDER BY id DESC LIMIT 1), 'Project Outreach and Communication Plan', 'Bond Cont. stakeholder engagement - Keyesport', '2024-09-15', NULL, 2000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-10' ORDER BY id DESC LIMIT 1), 'Hydraulics Data Capture', 'Bond Hydra Carlyle Lake & tributaries', '2022-08-15', NULL, 40000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-10' ORDER BY id DESC LIMIT 1), 'Independent QA/QC: Hydraulics Data', 'Bond Hydra QA/QC Carlyle Lake & tributaries', '2022-08-15', NULL, 4000.00, 0, 'active');

-- Project: ISWS 21-11
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-11', 'COMS SOW 21-11', '2022-03-01', '2023-09-15', 125000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-11' ORDER BY id DESC LIMIT 1), 'COMS Engagement Plan (required)', 'COMS Engagement Plan', '2022-03-01', NULL, 20000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-11' ORDER BY id DESC LIMIT 1), 'Strategic Planning for Community Engagement', 'Website Content Mod & Dev', '2023-09-15', NULL, 25000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-11' ORDER BY id DESC LIMIT 1), 'Training and Community Capability Development', 'Workshops, SAFR Guide & Video', '2023-09-15', NULL, 55000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-11' ORDER BY id DESC LIMIT 1), 'Mentoring', 'CTP program, Best practices, Tech solution sharing', '2023-09-15', NULL, 25000.00, 0, 'active');

-- Project: ISWS 21-12
INSERT INTO projects (grant_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES (14, 'ISWS 21-12', '21-12 Kishwaukee_Phase_2', '2022-12-15', '2025-09-15', 750000.00, 0, 'active');

INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-12' ORDER BY id DESC LIMIT 1), 'Project Management and Earned Value Data Entry', 'Kishwaukee PM', '2025-09-15', NULL, 2000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-12' ORDER BY id DESC LIMIT 1), 'Project Risk ID & Mitigation', 'Kishwaukee Prj risk control', '2025-09-15', NULL, 1000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-12' ORDER BY id DESC LIMIT 1), 'Project Outreach and Communication Plan', 'Kishwaukee Outreach and Communication', '2025-09-15', NULL, 4589.50, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-12' ORDER BY id DESC LIMIT 1), 'Event Data Capture (non-CCO / Open House)', 'PICC Meeting', '2022-12-15', NULL, 4000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-12' ORDER BY id DESC LIMIT 1), 'Event Data Capture (non-CCO / Open House)', 'Flood Risk Review Meeting', '2024-09-15', NULL, 14000.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-12' ORDER BY id DESC LIMIT 1), 'Survey Data Capture', 'Kishwaukee Phase 2 Survey', '2023-09-15', NULL, 306250.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-12' ORDER BY id DESC LIMIT 1), 'Independent QA/QC: Survey Data', 'Kishwaukee Phase 2 Survey QA/QC', '2023-09-15', NULL, 61250.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-12' ORDER BY id DESC LIMIT 1), 'Hydraulics Data Capture', 'Kishwaukee Phase 2 Hydraulics (Mainstem Kiswaukee River)', '2025-03-15', NULL, 315850.00, 0, 'active');
INSERT INTO tasks (project_id, name, description, start_date, end_date, budget, estimated_hours, status) VALUES ((SELECT id FROM projects WHERE name='ISWS 21-12' ORDER BY id DESC LIMIT 1), 'Independent QA/QC: Hydraulics Data', 'Kishwaukee Phase 2', '2025-03-15', NULL, 41060.50, 0, 'active');
